### PR TITLE
Feature/open source docs

### PR DESCRIPTION
**Pull request by bryancalisto**
### Content
Added files:
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- CODEOWNERS

### CODE REVIEW

**Review by cazabe — COMMENTED** [review]
Looks great! thanks, but do you think that the documentation must be in english, taking in consideration that is an Ecuadorian base project, perhaps we can add documentation also in spanish, basically translate what you already did, or manage documentation in just one language. What do you think?

**Comment by bryancalisto** [comment]
> Looks great! thanks, but do you think that the documentation must be in english, taking in consideration that is an Ecuadorian base project, perhaps we can add documentation also in spanish, basically translate what you already did, or manage documentation in just one language. What do you think?

Good point. I agree. Originally I though about adding the spanish stuff only in the main README, for users to consume easily, and keep anything developer-related in english for consistency, but what you say is true... Spanish is one of our cultural pillars. What about merging this PR and creating a new one with the spanish version? Do you want to work on that PR?

**Comment by cazabe** [comment]
> > Looks great! thanks, but do you think that the documentation must be in english, taking in consideration that is an Ecuadorian base project, perhaps we can add documentation also in spanish, basically translate what you already did, or manage documentation in just one language. What do you think?
> 
> Good point. I agree. Originally I though about adding the spanish stuff only in the main README, for users to consume easily, and keep anything developer-related in english for consistency, but what you say is true... Spanish is one of our cultural pillars. What about merging this PR and creating a new one with the spanish version? Do you want to work on that PR?

Ok, agree. And sure I would like to work on that PR

**Review by cazabe — COMMENTED** [review]
Approved

**Review by cazabe — APPROVED** [review]

**Pull request merged**
